baseURL = 'https://imcan.dev/'
languageCode = 'en-us'
title = 'Can Acar'
theme = 'myTheme'

[Params]
favicon_svg = "/images/favicon.svg"
favicon_ico = "/images/favicon.ico"
apple_touch_icon = "/images/apple-touch-icon.png"
navbarIcon = "/images/favicon.svg"

# Navigation Bar
[menu]
[[menu.navbar]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.navbar]]
    name = "Blog"
    url = "/blog"
    weight = 2
[[menu.navbar]]
    name = "Github"
    url = "https://github.com/droptopx"
    weight = 4
