baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Can Acar'
theme = 'myTheme'

[Params]
favicon = "/images/favicon.svg"
navbarIcon = "/images/favicon.svg"

# Navigation Bar
[menu]
[[menu.navbar]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.navbar]]
    name = "Vulns"
    url = "/vulns"
    weight = 2
[[menu.navbar]]
    name = "Github"
    url = "https://github.com/droptopx"
    weight = 3
[[menu.navbar]]
    name = "Contact"
    url = "/contact"
    weight = 4
